"""
=====================================================
Agent : Classifier Agent
Purpose : Determine document type
=====================================================
"""

from backend.document_processing.classifier_agent import (
    classify_document
)


# Classifier Node
# Determine document category
def classifier_agent(
        state
):

    # Read OCR text
    # Generated by OCR agent
    document_text = state[
        "document_text"
    ]

    # Classify document
    # Hotel flight taxi etc
    document_type = classify_document(
        document_text
    )

    # Store document type
    # Available for policy retrieval
    state[
        "document_type"
    ] = document_type

    # Return updated state
    return state