"""
=====================================================
Agent : PII Agent
Purpose : Detect sensitive information
=====================================================
"""

from backend.document_processing.pii_detector import (
    detect_pii
)


# PII Agent Node
# Detect sensitive information
def pii_agent(
        state
):

    # Read OCR output
    # Generated by OCR Agent
    document_text = state[
        "document_text"
    ]

    # Detect PII
    # Email phone etc
    findings = detect_pii(
        document_text
    )

    # Store findings
    # Available to next nodes
    state[
        "pii_findings"
    ] = findings

    # Return updated state
    return state